name: movie_browser_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  envied: ^1.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  http: ^1.5.0
  intl: ^0.19.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.7.0
  envied_generator: ^1.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
flutter:
  uses-material-design: true
